### ISSUE TITLE
Opracować pełną wersję specyfikacji wymagań (Software Requirement Specification, SRS) zgodną z zaleceniami IEEE 830-1998

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#11]
Panie @MichMaz25 , proszę opracować pełną wersję specyfikacji wymagań (Software Requirement
Specification, SRS) zgodną z zaleceniami IEEE 830-1998:

Opracować słownik projektu (z issue #7)
Przygotować listę wymagań funkcjonalnych i niefunkcjonalnych.  (z issue #8 )
Zidentyfikować aktorów  (z issue #6)
Przeprowadzić identyfikację przypadków użycia 
Opracować diagramy przypadków użycia

Deadline: 20-03-2016

**Comment by MichMaz25** [comment]
Zrobione

**Comment by bartkow** [comment]
Dziękuję

**Comment by bartkow** [comment]
Termin: 10-04-2016

**Comment by MichMaz25** [comment]
Zrobione
