### ISSUE TITLE
Opracować model fizyczny i konceptualny bazy danych

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#13]
Panie @michkar , proszę opracować model fizyczny i konceptualny bazy danych na podstawie pliku bluednvj_projekt.sql

Deadline: 25-03-2016

**Comment by bartkow** [comment]
Termin do: 10-04-2016

**Comment by MichMaz25** [comment]
Zrobione.
