### ISSUE TITLE
Określić stopnie uprawnień i możliwości dla użytkowników systemu

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#14]
Panie @MichMaz25, proszę o określenie stopni uprawnień i możliwości z tym związanych dla użytkowników systemu
Przykład:

> 1 - magazynier
> Możliwości: dodawanie i usuwanie towaru

Deadline: 25-03-2016

**Comment by MichMaz25** [comment]
zrobione

**Comment by bartkow** [comment]
Dobrze! Ale po terminie.
