### ISSUE TITLE
Opracować zapytania SQL do bazy danych

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#15]
Panie @niepolski, proszę o przygotowanie zapytań do bazy SQL dla:

- Logowania użytkownika (sprawdzenie czy nazwa użytkownika oraz hasło jest poprawne)
Zostaną podane parametry: $username oraz $password

- Pobrania informacji z bazy o typie uprawnień dla danego użytkownika
Zostanie podany parametr $_SESSION['username']

- Wyświetlenia spisu wszystkich kategorii

- Wyświetlenia spisu wszystkich użytkowników systemu

Kod bazy danych znajduje się w pliku: bluednvj_projekt.sql
Plik jest gotowy do zaimportowanie go do PHPmyAdmin

Deadline: 29-03-2016

**Comment by niepolski** [comment]
Done

**Comment by bartkow** [comment]
> WHERE nazwa LIKE $username AND haslo LIKE $password

> SELECT uzytkownik.uprawnienia WHERE nazwa LIKE $_SESSION['username']

> SELECT kategorie.nazwa 

> SELECT uzytkownik.nazwa

zapytania są błędne

**Comment by bartkow** [comment]
Termin: 05-04-2016
