### ISSUE TITLE
Opracować zapytania SQL do bazy danych 

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#16]
Panie @MichMaz25 , proszę o przygotowanie zapytań do bazy SQL dla:

- Dodania nowej kategorii do bazy
Zostanie podana nazwa poprzez $nazwa_kategorii

- Dodania nowego użytkownika do bazy
Zostaną podane parametry: $nazwa_uzytkownika, $haslo_md5, $uprawnienia

- Dodania nowego klienta do bazy
Zostaną podane parametry: $dane, $adres, $miasto, $kod, $telefon

- Dodania nowego towaru do bazy
Zostaną podane parametry: $nazwa,$cena,$kategoria,$ilosc,$ean
> `ilosc` ($ilosc) oraz `ilosc_akt` początkowo przyjmują taką samą wartość

- Dodania nowego zamówienia do bazy
Zostaną podane parametry: $id_produktu, $id_klienta, $ilosc, $koszt, $rabat, $koszt_calkowity, $data, $status

- Aktualizacji `ilosc_akt` po dodaniu zamówienia do danego produktu
Zostaną podane: $id_produktu, $ilosc_akt

- Wykasowania produktu z bazy
Zostanie podane tylko $id

Kod bazy danych znajduje się w pliku: bluednvj_projekt.sql
Plik jest gotowy do zaimportowanie go do PHPmyAdmin

Deadline: 29-03-2016

**Comment by MichMaz25** [comment]
zrobione

**Comment by bartkow** [comment]
Bardzo dobrze!
