### ISSUE TITLE
Test bazdy danych

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#17]
Panie @damraj, na podstawie issue #15 #16, proszę o test zapytań na gotowej bazie danych wraz ze szczegółowym raportem.

Raport z wykonanych testów, proszę zrobić na papierze projektowym i umieścić go w zakładce `code`

Kod bazy danych znajduje się w pliku: bluednvj_projekt.sql
Plik jest gotowy do zaimportowanie go do PHPmyAdmin

Deadline: 03-04-2016

Dane do logowania do bazy:
https://github.com/projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym/wiki/phpMyAdmin,-logowanie

**Comment by bartkow** [comment]
Dane do logowania do bazy:

https://github.com/projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym/wiki/phpMyAdmin,-logowanie

**Comment by damraj** [comment]
Nie mogę wykonać zadania, ponieważ issue wykonywane przez użytkownika "niepolski" jest błędne. Prosiłbym o przedłużenie terminu do jutra, napiszę wtedy issue i za niego, i za siebie.

**Comment by bartkow** [comment]
Wyrażam zgodę
Termin: 05-04-2016
