### ISSUE TITLE
[Pilne] - [PHP] - Łączenie z bazą

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#20]
Panie @damraj, proszę o pilne wykonanie fragmentu kodu w PHP, odpowiedzialnego za łączenie z bazą SQL. (funkcję)
Dane do logowanie zawarte są w pliku config.php

Podane zostaną: `$dbhost, $dbuser, $dbpass, $dbname, $db`

Deadline: 03-04-2016

Ze względu na pilość zadania, punktowane jest ono razy dwa.

**Comment by damraj** [comment]
Wykonano, jeszcze raz przepraszam za opóźnienie. Dziś nadrobię wszystkie zaległości bo w końcu odzyskałem możliwość użytku komputera.
