### ISSUE TITLE
[Pilne] - [PHP] - Sprawdzenie sesji

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#21]
Panie @MichMaz25 , proszę o pilne wykonanie fragmentu kodu w PHP, odpowiedzialnego za sprawdzenie, czy sesja dla użytkownika (username) jest utworzona. Jeśli nie, to powinno odbyć się przekierowanie do pliku 'blad-sesja.php'

Deadline: 31-03-2016

Ze względu na pilość zadania, punktowane jest ono razy dwa.

**Comment by MichMaz25** [comment]
zrobione

**Comment by bartkow** [comment]
Dziękuję. Dodaję 4 pkt
