### ISSUE TITLE
[TEST] - Zarządzanie kategoriami

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#26]
Termin: 24-04-2016

**Comment by damraj** [comment]
Myślałem, że się dziś wyrobię ale niestety dzień miałem bardziej zapracowany niż przypuszczałem. Jutro będzie wklejone po południu.

**Comment by bartkow** [comment]
Termin: 25-04-16  do końca dnia

**Comment by damraj** [comment]
Wykonano.

**Comment by michkar** [comment]
uuuuuuuuuuuuuuuu
