### ISSUE TITLE
Logotyp

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#3]
@damraj, proszę o wykonanie logotypu dla Naszej firmy, zawierający slogan od Pana @MichMaz25.
Wymiary max 256x256
Deadline: 07-03-2016

**Comment by damraj** [comment]
![logotajp](https://cloud.githubusercontent.com/assets/17563867/13575282/6e5b0820-e488-11e5-9f4b-9fee036a9734.png)
Proszę bardzo.
