### ISSUE TITLE
[INSTRUKCJA] - dwa etapy

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#36]
Panie @MichMaz25, proszę o stworzenie instrukcji dla przyszłego nabywcy oprogramowania

Aktualnie instrukcja powinna zawierać:
**Termin: 27-04-2016**
- Logowanie
- Konfiguracje początkową
- Dodawanie kategorii

_Wykonano etap I_

**Termin: 06-05-2016**
- Dodawanie produktów

**Termin: 11-05-2016**
- Dodawanie klientów

_Wykonano etap II_

Proszę o wykonanie tego na papierze firmowym, wraz ze szczegółowymi screenami. Proszę zachować składnię. Instrukcja powinna być prosta w zrozumieniu dla odbiorcy.

**Comment by MichMaz25** [comment]
Zrobione
