### ISSUE TITLE
Szablon firmowy do opracowania dokumentacji projektowej

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#4]
Panie @niepolski, na podstawie logotypu od Pana @damraj, proszę o przygotowanie szablonu firmowego do opracowania dokumentacji projektowej.

Deadline: 07-03-2016

**Comment by bartkow** [comment]
Panie @niepolski, deadline już dawno się skończył.

Proszę się pospieszyć. W innym przypadku zastosujemy karę umowną.

B.K.

**Comment by niepolski** [comment]
Wykonano

**Comment by niepolski** [comment]
[szablon firmowy.pdf](https://github.com/projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym/files/162761/szablon.firmowy.pdf)
