### ISSUE TITLE
Zidentyfikować aktorów

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#6]
Panie @damraj, proszę o zidentyfikowanie aktorów.

Deadline: 13-03-2016

**Comment by bartkow** [comment]
Proszę Pana.
Deadline się zakończył. Gdzie jest wykonanie issue?

**Comment by damraj** [comment]
Identyfikacja aktorów.


1) Administrator:
- Ilość towaru przechowywanego na magazynie
- Wyświetlenie złożonych zamówień
- Zarządzanie towarami
- Promocje
- Przechowywanie danych klientów
- Zarządzanie zamówieniami
- Importowanie/Exportowanie do bazy danych
- Dostęp do wszystkich funkcji w firmie
- Zmiana cen produktów

2) Magazynier:
- Przyjmowanie towaru od dostawcy do magazynu
- Iość towaru przechowywana w magazynie
- Możliwość zmiany statusu towaru
- Wyświetlenie złożonych zamówień
- Zarządzanie działami towarowymi

3) Klient
- Składanie zamówień
- Anulowanie zamówień
