### ISSUE TITLE
Opracować słownik projektu .

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#7]
Panie @MichMaz25, proszę o opracowanie słownika projektu

Deadline: 13-03-2016

**Comment by MichMaz25** [comment]
Pojęcia użyte w aplikacji.

**Comment by bartkow** [comment]
Ma Pan rację.
Pozdrawiam
B.K.

**Comment by MichMaz25** [comment]
Karta graficzna – karta rozszerzeń komputera odpowiedzialna za renderowanie grafiki i jej konwersję na sygnał zrozumiały dla wyświetlacza.
Procesor (CPU - centralna jednostka wykonawcza) to układ scalony, którego działanie polega na wykonywaniu instrukcji programów. Nadzoruje on i synchronizuje prace wszystkich urządzen w komputerze.
Pendrive-urządzenie przenośne zawierające pamięć nieulotną typu flash, zaprojektowane do współpracy z komputerem przez port USB i używane do przenoszenia danych między komputerami oraz urządzeniami obsługującymi pamięci USB.
Sprzęt komputerowy (ang. hardware) – materialna część komputera. Ogólnie hardware'em nazywa się sprzęt komputerowy jako taki i odróżnia się go od software'u – czyli oprogramowania.
 Dysk twardy- rodzaj pamięci masowej, wykorzystujący nośnik magnetyczny do przechowywania danych. Nazwa "dysk twardy" wynika z zastosowania twardego materiału jako podłoża dla właściwego nośnika
Monitor komputerowy – ogólna nazwa jednego z urządzeń wyjścia do bezpośredniej komunikacji użytkownika z komputerem. Zadaniem monitora jest natychmiastowa wizualizacja wyników działania programów uruchomionych na komputerze.
Klawiatura komputerowa – uporządkowany zestaw klawiszy służący do ręcznego sterowania urządzeniem lub ręcznego wprowadzania danych.
Mysz (z ang. mouse) – urządzenie wskazujące używane podczas pracy z interfejsem graficznym systemu komputerowego.

**Comment by MichMaz25** [comment]
Wykonane.

Pozdrawiam
M.M

**Comment by bartkow** [comment]
Dziękuję
B.K.
