### ISSUE TITLE
Przygotować listę wymagań funkcjonalnych i niefunkcjonalnych

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/Zarzadzanie-Sklepem-Komputerowym#8]
Panie @niepolski, proszę przygotować listę wymagań funkcjonalnych i niefunkcjonalnych

Deadline 13-03-2016, tym razem proszę wykonać to na czas.

**Comment by bartkow** [comment]
Proszę Pana.
Deadline się zakończył. Gdzie jest wykonanie issue?

**Comment by bartkow** [comment]
من فضلك، يا رب.
الموعد النهائي هو أكثر. أين هي المشكلة ؟

**Comment by niepolski** [comment]
أنا آسف على التأخير. وسوف أبذل قصارى جهدي للا تفعل هذا مرة أخرى

**Comment by bartkow** [comment]
Dziękuję
